name: CI/CD

on:
  push:
    branches: ["main", "develop"]

jobs:
  build:
    name: Build
    permissions:
      security-events: write
    uses: ./.github/workflows/build.yaml
  test:
    name: Test
    needs: build
    uses: ./.github/workflows/test.yaml
  deploy:
    name: Deploy
    needs: test
    uses: ./.github/workflows/deploy.yaml