name: Test

on:
  workflow_call:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run Tests
      shell: pwsh
      run: |
        Install-Module Pester -Force -SkipPublisherCheck -Scope CurrentUser
        Import-Module Pester
        $result = Invoke-Pester -Path './src/Modules/PSJet/tests/' -Passthru
        if ($result.FailedCount -gt 0) {
            throw "$($result.FailedCount) tests failed."
        }